version: '3.3'

services:
  # Frontend service for development
  frontend-dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    networks:
      - short-link-network

  # Frontend service for production
  frontend-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod
    networks:
      - short-link-network

  # Optional: Add database service if needed
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: shortlink
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - short-link-network

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - short-link-network

networks:
  short-link-network:
    driver: bridge

# volumes:
#   postgres_data:
